document.write("<style>");
document.write("body {background:#E9EAED url(\"asd.jpg\");}");
document.write("a:link, a:visited { color: #3A5795; text-decoration: none; font-weight: normal; }");
document.write("a:active, a:hover { color: rgb(0, 153, 0); text-decoration: underline; }");
document.write("#templatmeo_wrapper { width: 850px; margin: 30px auto;overflow:hidden; }");
document.write("#nuzulhook_header { border:1px solid #D3D6DB;clear: both; width: 850px; height: 360px; padding: 0px 0px; background:#fff url(\"https:\/\/sites.google.com\/site\/nuzulz\/download\/headerkampuscunair.jpg\") repeat scroll 0% 0%; }");
document.write("#nuzulhook_header_top {height:300px;background:#000 url(\"https:\/\/sites.google.com\/site\/nuzulz\/download\/headerkampuscunair.jpg\");overflow:hidden;}");
document.write("#nuzulhook_header_top_image {height:300px;}");
document.write("#nuzulhook_header_top_trans {height:300px;background:url('https:\/\/sites.google.com\/site\/nuzulz\/download\/trans.png') repeat-x scroll left 0px bottom -1px transparent;position:relative;top:-300px;}");
document.write("#nuzulhook_header_top_line {height:10px;background:yellow;position:relative;top:-310px;}");
document.write("#nuzulhook_header_top_search {height:0px;position:relative;top:-600px;}");
document.write("#search_form {float:right;margin-right:10px;}");
document.write("#nuzulhook_header_bottom {height:60px;background:#fff;}");
document.write("#nuzulhook_header_poto {border:3px solid #D3D6DB;width:150px;height:150px;background:#fff;position:relative;top:-170px;left:30px;overflow:hidden;}");
document.write("#nuzulhook_header_title{position:relative;top:-280px;left:200px;color:#fff;}");
document.write("#nuzulhook_header_title h2 {font-family:\"Trebuchet MS\", Arial, Sans-serif;font-size:250%;}");
document.write("#liketwitteratas {position:relative;top:-18px;left:170px;height:0px;}");
document.write("#nuzulhook_header_menu{position:relative;top:-250px;left:200px;color:#000;}");
document.write("#nuzulhook_content_wrapper { clear: both; padding: 0px;margin-top:10px; }");
document.write("#nuzulhook_sidebar { float: left; margin-right: 10px; width: 340px; }");
document.write("#nuzulhook_content { float: left; width: 500px; }");
document.write("#nuzulhook_box {border:1px solid #D3D6DB;margin-bottom: 10px; background:#fff ;}");
document.write("");
document.write(".templatemo_box { border:1px solid #D3D6DB;margin-bottom: 10px; background:#fff ; }");
document.write(".templatemo_box .body { padding: 5px 15px; }");
document.write(".templatemo_box h2 { position: relative; height: 25px; margin: 0px; padding: 8px 15px; font-size: 14px; color: #4E5665; font-weight: bold; background:#F6F7F8  }");
document.write(".templatemo_box h2 span { position: absolute; width: 10px; height: 35px; top: 0px; left: 0px; background: url(\"\") repeat scroll 0% 0% transparent; }");
document.write(".templatemo_box .box_bottom { position: relative; height: 12px; background: url(\"\") repeat scroll right top transparent; }");
document.write(".templatemo_box .box_bottom span { position: absolute; width: 10px; height: 12px; top: 0px; left: 0px; background: url(\"\") repeat scroll 0% 0% transparent; }");
document.write(".more a{background:#E9EAED}");
document.write(".side_menu li { padding: 0px; margin: 5px 0px;border-left:2px solid #000 }");
document.write(".side_menu li a {background:url();}");
document.write("");
document.write("#nuzulhook_sidebar .templatemo_box {height: 32px; overflow: hidden;}");
document.write("#nuzulhook_sidebar .templatemo_box:hover {height:100%}");
document.write("#nuzulhook_sidebar_bottom .templatemo_box {height: 32px; overflow: hidden;}");
document.write("#nuzulhook_sidebar_bottom .templatemo_box:hover {height:100%}");
document.write("");
document.write("#templatemo_footer {width:0px;}");
document.write("#nuzulhook_footer { border:1px solid #D3D6DB;clear: both; width: 830px; height: 100%; padding: 10px; background:#fff;font-size:80%;line-height:1em; }");
document.write("");
document.write("#menupopup1{overflow:hidden;width:640px;height:40px;padding:5px 0 0 0}#menupopup1,#menupopup1 ul li:hover ul.child li a{background:#fff}#menupopup1 ul{margin:0 -40px;}#menupopup1 ul li{margin:0 5px 0 5px; border-right:1px solid #4E5665;}#menupopup1 ul li{list-style-type:none;float:left}#menupopup1 ul li a{font:14px arial;text-decoration:none;margin:0 10px 0 0;color:#4E5665}#menupopup1 ul li ul.child{display:none}#menupopup1 ul li:hover ul.child,#menupopup1 ul li:hover ul.child li a{display:block}#menupopup1 ul li:hover ul.child{position:absolute;z-index:2;text-align:left}#menupopup1 ul li:hover ul.child li a{padding:10px 20px 10px 20px;margin:0 0 0 10px}#menupopup1 ul li:hover ul.child li{float:none;margin:0 0 0 -30px}#menupopup1 ul li a:hover{text-decoration:underline}");
document.write("");
document.write("#pages {margin-bottom:10px;}");
document.write(".navigation{display:block;overflow:hidden;width:100%;height:auto;padding:5px 20px 5px !important;clear:both !important;}");
document.write(".page-numbers{padding:4px 9px 4px 9px !important;border:solid 1px #DCDCDC !important;border-color:#3390CA !important;order-radius:3px !important;-moz-border-radius:3px !important;-webkit-border-radius:3px !important;color:#fff !important;margin-right:3px !important;border-color:#478223 !important;background:#599F2F !important;background:-moz-linear-gradient(top,#9FE355 1px,#79BF4A 1px,#599F2F) !important;background:-webkit-gradient(linear,0 0,0 100%,color-stop(0.02,#9FE355),color-stop(0.02,#79BF4A),color-stop(1,#599F2F)) !important;}");
document.write(".navigation a{color:#707070 !important;background:#FFFFFF !important;border-radius:3px !important;-moz-border-radius:3px !important;-webkit-border-radius:3px !important;padding:6px 9px 6px 9px !important;margin-right:3px !important;text-decoration:none !important;font-size:12px !important;}");
document.write(".navigation a:hover{color:#fff !important;border-color:#478223 !important;background:#599F2F !important;background:-moz-linear-gradient(top,#048DC6 1px,#048DC6 1px,#048DC6) !important;background:-webkit-gradient(linear,0 0,0 100%,color-stop(0.02,#9FE355),color-stop(0.02,#79BF4A),color-stop(1,#599F2F)) !important;}");
document.write("<\/style>");
