document.write("<head><link rel=\"shortcut icon\" type=\"image\/x-icon\" href=\"http:\/\/web.unair.ac.id\/images\/unair.ico\" \/><\/head>");
document.write("");
document.write("<div style=\"overflow:auto;\">");
document.write("<!-- gambar unair -->");
document.write("<!--<a href=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_blogger-unair-2.jpg\" title=\"Nuzulul Zulkarnain Haq\" ><img src=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_blogger-unair-2.jpg\" width=\"100%\"><\/a>--><style>ul#navigation1{position:fixed;margin:0 auto 0 180px;padding:0;top:0;left:auto;right:auto;list-style:none;z-index:999999;width:550px}ul#navigation1 li{width:103px;display:inline;border:0}ul#navigation1 li,ul#navigation1 li a{float:left}ul#navigation1 li a{background:#048dc6 no-repeat 50% 10px;display:block;color:#fff;margin-top:-2px;width:100px;height:25px;border:1px solid #bddcef;-moz-border-radius:0 0 10px 10px;-webkit-border-bottom-right-radius:10px;-webkit-border-bottom-left-radius:10px;-khtml-border-bottom-right-radius:10px;-khtml-border-bottom-left-radius:10px;text-decoration:none;text-align:center;padding-top:15px;opacity:0.96;filter:progid:DXImageTransform.Microsoft.Alpha(opacity=70)}ul#navigation1 li a:hover{background:#000}ul#navigation1 li a span{font:11px trebuchet-ms,arial,tahoma,sans-serif bold;letter-spacing:2px;color:#60acd8;text-shadow:0 -1px 1px #fff}body,#templatemo_footer_wrapper{background:#000}#templatmeo_wrapper{width:970px;margin:100px auto 10px auto;background:#e5e5e5;padding-bottom:20px;}#templatemo_header{clear:both;width:910px;height:300px;padding:10px 30px;background:#fff}#templatemo_header  #site_title{padding-top:40px;padding-left:70px}#templatemo_banner{display:none}#templatemo_menu{display:none}#templatemo_footer{background:#048dc6}#templatemo_footer_wrapper{margin:10px auto 60px auto;}#templatemo_header  #site_title h1{font-size:90%;font: 'Trebuchet MS', Arial, Sans-serif;padding: 10px 0 0 12px;}#templatemo_header  #site_title h2 {font: bolder 4.1em 'Trebuchet MS', Arial, Sans-serif;padding: 0px 0 0 10px;}#templatemo_footer {text-align: right;color: #666666;padding:10px 10px;color:#048DC6;background:#048DC6;}#counterblog{display:none}");
document.write("#templatemo_footer a {color:#fff;}#templatemo_footer .footer_menu {margin: 0 0 0px 0;}<\/style>");
document.write("<!-- end of gambar unair -->");
document.write("<!--");
document.write("<marquee behavior=\"scroll\" direction=\"up\" scrollamount=\"2\" width=\"100%\" height=\"150\" onmouseover=\"this.stop();\" onmouseout=\"this.start();\"><ul class=\"side_menu\">");
document.write("<li><a href=\"http:\/\/web.unair.ac.id\/berita_lengkap.php?id=2\">Lomba Blog Mahasiswa Universitas Airlangga 2011<\/a><\/li>");
document.write("<li><a href=\"http:\/\/web.unair.ac.id\/berita_lengkap.php?id=1\">Selamat Bergabung di Blog Unair<\/a><\/li>                   ");
document.write("<\/ul>");
document.write("<\/marquee> -->");
document.write("");
document.write("<!-- menu nzl ");
document.write("<ul id=\"navigation1\">");
document.write("<li class=\"home\"><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/index.html\">Home<\/a><\/li>");
document.write("<li class=\"buku\"><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24186.html\">Buku Tamu<\/a><\/li>");
document.write("<li class=\"admin\"><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24185.html\">Admin<\/a><\/li>");
document.write("<li class=\"profil\"><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/profil.html\">Profile<\/a><\/li>");
document.write("<li class=\"unair\"><a href=\"http:\/\/unair.ac.id\">Unair<\/a><\/li>");
document.write("<\/ul>");
document.write(" end -->");
document.write("<div id=\"counterblog\">");
document.write("");
document.write("<!-- Site Meter -->");
document.write("<a href=\"http:\/\/s12.sitemeter.com\/stats.asp?site=s12nuzulul\" target=\"_top\">");
document.write("<img src=\"http:\/\/s12.sitemeter.com\/meter.asp?site=s12nuzulul\" alt=\"Site Meter\" border=\"0\"\/><\/a>-->");
document.write("<!-- Copyright (c)2009 Site Meter -->");
document.write("<!--  Your Page ID: 203656 --><!-- <img style=\"border: 0px\" src=\"http:\/\/www.webcounterstats.com\/count.php?page=203656\" \/><br \/><a href=\"http:\/\/www.laseraid.com.au\" target=\"_blank\" title=\"candela\" style=\"font-family: Geneva, Arial, Helvetica, sans-serif; font-size: 10px; text-decoration: none; color: #314321\">candela<\/a>   -->");
document.write("");
document.write("<\/div><\/div>");
document.write("");
document.write("<div style=\"width:150px;height:70px;color:yellow;background:blue;right:-48px;top:-5px;position:fixed;z-index:999999;-moz-transform:rotate(45deg);transform:rotate(45deg);-ms-transform:rotate(45deg);-webkit-transform:rotate(45deg);-o-transform:rotate(45deg);\"><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-36168.html\" title=\"Pasang Widget Blogger Unair\" target=\"_blank\"><img src=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_blogger-unair-2.jpg\"><\/a><\/div>");
document.write("");
document.write("<style>#menupopup1{width:auto;height:20px;padding:5px 0 0 0}#menupopup1,#menupopup1 ul li:hover ul.child li a{background:#048dc6}#menupopup1 ul,#menupopup1 ul li{margin:0}#menupopup1 ul li{list-style-type:none;float:left}#menupopup1 ul li a{font:12px arial;text-decoration:none;margin:0 10px 0 0;color:#fff}#menupopup1 ul li ul.child{display:none}#menupopup1 ul li:hover ul.child,#menupopup1 ul li:hover ul.child li a{display:block}#menupopup1 ul li:hover ul.child{position:absolute;z-index:2;text-align:left}#menupopup1 ul li:hover ul.child li a{padding:10px 20px 10px 20px;margin:0 0 0 -20px}#menupopup1 ul li:hover ul.child li{float:none;margin:0 0 0 -30px}#menupopup1 ul li a:hover{text-decoration:underline}<\/style>");
document.write("");
document.write("");
document.write("<div style=\"width:920px;height:20px;left:auto;right:auto;top:110px;position:absolute;\">");
document.write("<div id=\"menupopup1\">");
document.write("	<ul class=\"parent\">");
document.write("		<li><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\">Home<\/a><\/li>");
document.write("		<li><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24176.html\">About<\/a><\/li>");
document.write("		<li><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24186.html\">Buku Tamu<\/a><\/li>");
document.write("                <li><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24185.html\">Askep<\/a><\/li>");
document.write("                <li><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24183.html\">Sahabat<\/a><\/li>");
document.write("                <li><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24192.html\">Download<\/a><\/li>");
document.write("                <li><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24196.html\">Album<\/a><\/li>");
document.write("                <li><a href=\"#\">More<\/a>");
document.write("                <ul class=\"child\">");
document.write("		            <li><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/profil.html\">Profile<\/a><\/li>");
document.write("                            <li><a href=\"http:\/\/www.google.com\/cse?cx=002432522631165541499%3Aokf_w9ptqto&ie=UTF-8&q=site%3Anuzulul-fkp09.web.unair.ac.id&sa=Telusuri&siteurl=nuzulul-fkp09.web.unair.ac.id%2F#gsc.tab=0&gsc.q=site%3Anuzulul-fkp09.web.unair.ac.id&gsc.page=1\" target=\"_blank\">Daftar Isi<\/a><\/li>");
document.write("               <\/ul>");
document.write("               <\/li>		");
document.write("	<\/ul>");
document.write("<\/div>");
document.write("<div style=\"width:250px;height:20px;left:700px;top:-25px;color:white;position:relative;\">");
document.write("<form action=\"http:\/\/www.google.com\/cse\" id=\"cse-search-box\" target=\"_blank\"><div>");
document.write("<input type=\"hidden\" name=\"cx\" value=\"002432522631165541499:okf_w9ptqto\" \/>");
document.write("<input type=\"hidden\" name=\"ie\" value=\"UTF-8\" \/>");
document.write("<input type=\"text\" name=\"q\" size=\"20\" \/>");
document.write("<input type=\"submit\" name=\"sa\" value=\"Search\" \/><\/div><\/form>");
document.write("<script type=\"text\/javascript\" src=\"http:\/\/www.google.com\/cse\/brand?form=cse-search-box&lang=id\"><\/script><\/div>");
document.write("<div style=\"width:100px;height:auto;left:auto;right:auto;top:40px;position:absolute;\"><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24176.html\"><img src=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_wanted-nuzulul-zulkarnain-haq-010212.jpg\" width=\"70px\"><\/a>");
document.write("<div style=\"width:250px;height:50px;left:705px;top:-55px;position:relative;\">");
document.write("<a href=\"http:\/\/www.facebook.com\/nuzulhook\" target=\"_blank\"><img src=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_logo-fb.jpg\" width=\"50px\"><\/a>");
document.write("<a href=\"http:\/\/www.twitter.com\/nuzulhook\" target=\"_blank\"><img src=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_logo-twitter.jpg\" width=\"50px\"><\/a>");
document.write("<a href=\"http:\/\/www.youtube.com\/user\/nuzulhook\" target=\"_blank\"><img src=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_youtube_logo.png\" width=\"50px\"><\/a>");
document.write("<a href=\"https:\/\/plus.google.com\/113810582017056258327?rel=author\" target=\"_blank\"><img src=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_google_plus_logo.jpg\" width=\"50px\"><\/a>");
document.write("<\/div>");
document.write("<\/div>");
document.write("");
document.write("<div id=\"GambarBackground\" style=\"background-image: url(http:\/\/web.unair.ac.id\/admin\/file\/f_13693_rektorat-unair-nuzulul-zulkarnain-haq.jpg);overflow:hidden;background:#93BDF5;width:920px;height:150px;left:auto;right:auto;top:150px;position:absolute;\"><center><a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/\"><img id=\"GambarDasar\" style=\"opacity: 0;\" src=\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_rektorat-unair-nuzulul-zulkarnain-haq.jpg\" width=\"920px\"><\/a><\/center><\/div>");
document.write("");
document.write("<div style=\"width:150px;height:25px;left:690px;top:40px;position:absolute;overflow:hidden;\">");
document.write("<div id=\"likefbatas\"><a href=\"http:\/\/facebook.com\/nuzululzulkarnainhaq\/\">facebook<\/a><\/div>");
document.write("<\/div>");
document.write("");
document.write("<div style=\"width:150px;height:25px;left:780px;top:40px;position:absolute;overflow:hidden;\">");
document.write("<div id=\"liketwitteratas\"><a href=\"http:\/\/twitter.com\/nuzulhook\/\">twitter<\/a><\/div>");
document.write("<\/div>");
document.write("");
document.write("<div style=\"width:230px;height:215px;left:705px;top:320px;background:#E5E5E5;position:absolute;overflow:hidden;z-index:999999;\">");
document.write("<div class=\"templatemo_box\">");
document.write("<h2><span><\/span>Welcome Note<\/h2>");
document.write("<div class=\"body\"><div style=\"width:100%;height:100%;display:block;\">");
document.write("<p>.: engkau tak mendapatkan rahasia perjuangan dari buku-buku dan kata orang, tapi dari pahit getir perjuangan :. <a href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24176.html\">more<\/a><\/br><\/br>contact : <a target=\"_blank\" href=\"http:\/\/facebook.com\/nuzulhook\">facebook<\/a> & <a target=\"_blank\"  href=\"http:\/\/twitter.com\/nuzulhook\">twitter<\/a><\/p>");
document.write("<\/div><\/div><div class=\"box_bottom\"><span><\/span><\/div><\/div><\/div>");
document.write("");
document.write("<\/div>");
document.write("");
document.write("");
document.write("");
document.write("<style>");
document.write("#templatemo_content .templatemo_box h2 span { position: absolute; width: 5px; height: 5px; top: 0pt; left: 0pt; background: url(\"templatemo_box_tl.jpg\") repeat scroll 0% 0% transparent; }");
document.write("#templatemo_content .templatemo_box h2 { position: relative; height: 25px; margin: 0pt; padding: 8px 15px 25px 60px; font-size: 14px; color: rgb(4, 141, 198); font-weight: bold; background: url(\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_gajah3.jpg\") no-repeat scroll left top transparent; }");
document.write("<\/style>");
document.write("");
document.write("   <!-- Histats.com  (div with counter) --><div id=\"histats_counter\"><\/div>");
document.write("<!-- Histats.com  START  (aync)-->");
document.write("<script type=\"text\/javascript\">var _Hasync= _Hasync|| [];");
document.write("_Hasync.push(['Histats.start', '1,1977852,4,202,118,45,00010001']);");
document.write("_Hasync.push(['Histats.fasi', '1']);");
document.write("_Hasync.push(['Histats.track_hits', '']);");
document.write("(function() {");
document.write("var hs = document.createElement('script'); hs.type = 'text\/javascript'; hs.async = true;");
document.write("hs.src = ('http:\/\/s10.histats.com\/js15_as.js');");
document.write("(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(hs);");
document.write("})();<\/script>");
document.write("<noscript><a href=\"http:\/\/www.histats.com\" target=\"_blank\"><img  src=\"http:\/\/sstatic1.histats.com\/0.gif?1977852&101\" alt=\"free stats\" border=\"0\"><\/a><\/noscript>");
document.write("<!-- Histats.com  END  -->");
document.write("");
document.write("<div id=\"bukutamufbnuzul\" style=\"padding:10px 10px;position:fixed;width:700px;top:30px;left:auto;right:auto;margin:30px auto auto auto;height:500px;background:#048DC6;z-index:999999;display:none;overflow:scroll;\">");
document.write("<div style=\"padding:0px 10px 10px 0px;color:white;\"><div style=\"color:white;width:50px;float:right;\"><a style=\"color:white;\" onmouseup=\"document.getElementById('bukutamufbnuzul').style.display='none'\" href=\"#\">(x)Close<\/a><\/div><h1>BUKU TAMU<\/h1> <\/div>");
document.write("<div style=\"background:white;padding:10px 10px 10px 10px;\"><div class=\"fb-comments\" data-href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/\" data-width=\"650\" data-num-posts=\"10\"><\/div><\/div>");
document.write("<\/div>");
document.write("");
document.write("<div id=\"bukupesanfbnuzul\" style=\"padding:10px 10px;position:fixed;width:700px;top:30px;left:auto;right:auto;margin:30px auto auto auto;height:500px;background:#048DC6;z-index:999999;display:none;overflow:scroll;\">");
document.write("<div style=\"padding:0px 10px 10px 0px;color:white;\"><div style=\"color:white;width:50px;float:right;\"><a style=\"color:white;\" onmouseup=\"document.getElementById('bukupesanfbnuzul').style.display='none'\" href=\"#\">(x)Close<\/a><\/div><h1>PESAN<\/h1> <\/div>");
document.write("<div style=\"background:white;padding:10px 10px 10px 10px;\"><div class=\"fb-comments\" data-href=\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/\" data-width=\"650\" data-num-posts=\"10\"><\/div>");
document.write("<\/div>");
document.write("<\/div>");
document.write("");
document.write("<script language=\"JavaScript\" type=\"text\/javascript\" >");
document.write("var FadeDurationMS=1000;");
document.write("function SetOpacity(object,opacityPct)");
document.write("{object.style.filter='alpha(opacity='+opacityPct+')';object.style.MozOpacity=opacityPct\/100;object.style.opacity=opacityPct\/100;object.style.width='920px';}");
document.write("");
document.write("function ChangeOpacity(id,msDuration,msStart,fromO,toO)");
document.write("{var element=document.getElementById(id);var msNow=(new Date()).getTime();var opacity=fromO+(toO-fromO)*(msNow-msStart)\/msDuration;if(opacity>=100)");
document.write("{SetOpacity(element,100);element.timer=undefined;}");
document.write("else if(opacity<=0)");
document.write("{SetOpacity(element,0);element.timer=undefined;}");
document.write("else");
document.write("{SetOpacity(element,opacity);element.timer=window.setTimeout(\"ChangeOpacity('\"+id+\"',\"+msDuration+\",\"+msStart+\",\"+fromO+\",\"+toO+\")\",10);}}");
document.write("");
document.write("function FadeInImage(foregroundID,newImage,backgroundID)");
document.write("{var foreground=document.getElementById(foregroundID);if(foreground.timer)window.clearTimeout(foreground.timer);if(backgroundID)");
document.write("{var background=document.getElementById(backgroundID);if(background)");
document.write("{if(background.src)");
document.write("{foreground.src=background.src;SetOpacity(foreground,100);}");
document.write("background.src=newImage;background.style.backgroundImage='url('+newImage+')';background.style.backgroundRepeat='repeat';background.style.backgroundPosition='center center';var startMS=(new Date()).getTime();foreground.timer=window.setTimeout(\"ChangeOpacity('\"+foregroundID+\"',\"+FadeDurationMS+\",\"+startMS+\",100,0)\",10);}}else{foreground.src=newImage;}}");
document.write("var slideCache=new Array();");
document.write("");
document.write("function RunSlideShow(pictureID,backgroundID,imageFiles,displaySecs)");
document.write("{var imageSeparator=imageFiles.indexOf(\";\");var nextImage=imageFiles.substring(0,imageSeparator);FadeInImage(pictureID,nextImage,backgroundID);var futureImages=imageFiles.substring(imageSeparator+1,imageFiles.length)");
document.write("+';'+nextImage;setTimeout(\"RunSlideShow('\"+pictureID+\"','\"+backgroundID+\"','\"+futureImages+\"',\"+displaySecs+\")\",displaySecs*1000);imageSeparator=futureImages.indexOf(\";\");nextImage=futureImages.substring(0,imageSeparator);if(slideCache[nextImage]==null)");
document.write("{slideCache[nextImage]=new Image;slideCache[nextImage].src=nextImage;}}");
document.write("");
document.write("RunSlideShow(\"GambarDasar\",\"GambarBackground\",\"http:\/\/web.unair.ac.id\/admin\/file\/f_13693_rektorat-unair-nuzulul-zulkarnain-haq.jpg;http:\/\/web.unair.ac.id\/admin\/file\/f_13693_bemunairfarewell.jpg\",5);");
document.write("<\/script>");
document.write("");
document.write("<div id=\"fb-root\"><\/div>");
document.write("<style>");
document.write("#nuzulul_footer_wrapper {");
document.write("	width: 970px;");
document.write("padding:5px 0 5px 0;");
document.write("	margin: 10px auto 60px auto;");
document.write("	text-align: left;");
document.write("	color: #000;");
document.write("font-size:10px;");
document.write("line-height:1em;");
document.write("         background:#E5E5E5;");
document.write("}");
document.write("");
document.write("#nuzulul_footer_wrapper a {");
document.write("color:white;");
document.write("}");
document.write("#nuzulul_friend {");
document.write("margin:0px 5px;");
document.write("padding:10px 10px;");
document.write("background: #048dc6;");
document.write("color:#fff;");
document.write("}");
document.write("#nuzulul_friend_likeface{");
document.write("height:70px;");
document.write("overflow:hidden;");
document.write("}");
document.write("#nuzulul_friend_box{");
document.write("width:70px;");
document.write("height:70px;");
document.write("overflow:hidden;");
document.write("float:left;");
document.write("}");
document.write("#nuzulul_likebox {");
document.write("margin:5px 5px;");
document.write("padding:10px 10px;");
document.write("background: #fff;");
document.write("color:#fff;");
document.write("}");
document.write("#nuzulul_likebox_colum {");
document.write("width:310px;");
document.write("height:300px;");
document.write("float:left;");
document.write("}");
document.write("#nuzulul_footer {");
document.write("margin:5px 5px;");
document.write("padding:10px 10px;");
document.write("background: #048dc6;");
document.write("color:#fff;");
document.write("}");
document.write("#nuzulul_footer_nav {");
document.write("margin:5px 5px;");
document.write("padding:0px 0px;");
document.write("background: #048dc6;");
document.write("color:#fff;");
document.write("height:2.2em;");
document.write("line-height:2.2em;");
document.write("}");
document.write("#nuzulul_footer_nav li {");
document.write("float:left;");
document.write("list-style-type:none;");
document.write("border-right:1px solid rgb(255, 255, 255);");
document.write("padding-right:10px;");
document.write("padding-left:10px;");
document.write("}");
document.write("#nuzulul_footer_nav a{");
document.write("color:white;");
document.write("}");
document.write("");
document.write("#pages {width:425px;height:1px;left:250px;top:-48px;position:relative;line-height: 2.2em;}");
document.write("");
document.write(".navigation{display:block;overflow:hidden;width:100%;height:auto;padding:5px 20px 5px !important;clear:both !important;}");
document.write(".page-numbers{padding:4px 9px 4px 9px !important;border:solid 1px #DCDCDC !important;border-color:#3390CA !important;order-radius:3px !important;-moz-border-radius:3px !important;-webkit-border-radius:3px !important;color:#fff !important;margin-right:3px !important;border-color:#478223 !important;background:#599F2F !important;background:-moz-linear-gradient(top,#9FE355 1px,#79BF4A 1px,#599F2F) !important;background:-webkit-gradient(linear,0 0,0 100%,color-stop(0.02,#9FE355),color-stop(0.02,#79BF4A),color-stop(1,#599F2F)) !important;}");
document.write(".navigation a{color:#707070 !important;background:#FFFFFF !important;border-radius:3px !important;-moz-border-radius:3px !important;-webkit-border-radius:3px !important;padding:6px 9px 6px 9px !important;margin-right:3px !important;text-decoration:none !important;font-size:12px !important;}");
document.write(".navigation a:hover{color:#fff !important;border-color:#478223 !important;background:#599F2F !important;background:-moz-linear-gradient(top,#048DC6 1px,#048DC6 1px,#048DC6) !important;background:-webkit-gradient(linear,0 0,0 100%,color-stop(0.02,#9FE355),color-stop(0.02,#79BF4A),color-stop(1,#599F2F)) !important;}");
document.write("");
document.write("<\/style>");
document.write("");
document.write("");
document.write("<script>");
document.write("function show_alert() {");
document.write("  if(confirm(\"Apakah anda yakin?\"))");
document.write("    document.getElementsByName('form3')[0].submit();");
document.write("  else");
document.write("    return false;");
document.write("}");
document.write("");
document.write("function loadScript()");
document.write("{");
document.write("");
document.write("document.getElementById('likefbatas').innerHTML = \"<div id=\\"likefbatas\\"><iframe src=\\"\/\/www.facebook.com\/plugins\/like.php?href=http%3A%2F%2Ffacebook.com%2Fnuzulhook&send=false&layout=button_count&width=100&show_faces=false&font&colorscheme=light&action=like&height=21&appId=172259479541279\\" scrolling=\\"no\\" frameborder=\\"0\\" style=\\"border:none; overflow:hidden; width:100px; height:90px;\\" allowTransparency=\\"true\\"><\\/iframe><\\/div>\";");
document.write("");
document.write("document.getElementById('liketwitteratas').innerHTML = \"<div id=\\"liketwitteratas\\"><iframe src=\\"\/\/nuzulul.github.com\/ngawur\/liketwitter.html\\" scrolling=\\"no\\" frameborder=\\"0\\" style=\\"border:none; overflow:hidden; width:200px; height:90px;\\" allowTransparency=\\"true\\"><\\/iframe><\\/div>\";");
document.write("");
document.write("document.getElementById('templatemo_footer_wrapper').innerHTML = \"<div id=\\"nuzulul_footer_wrapper\\"><div id=\\"pages\\"><div class=\\"navigation\\"><a class=\\"page-numbers\\" href=\\"index.html?hal=1\\">1<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=2\\">2<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=3\\">3<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=4\\">4<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=5\\">5<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=6\\">6<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=7\\">7<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=8\\">8<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=9\\">9<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=10\\">10<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=11\\">11<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=12\\">12<\\/a><a class=\\"page-numbers\\" href=\\"index.html?hal=13\\">13<\\/a><\\/div><\\/div><div id=\\"nuzulul_friend\\"><div id=\\"nuzulul_friend_box\\"><iframe src=\\"\/\/www.facebook.com\/plugins\/like.php?href=https%3A%2F%2Ffacebook.com%2Fnuzulhook&send=false&layout=box_count&width=100&show_faces=true&font&colorscheme=light&action=like&height=90&appId=172259479541279\\" scrolling=\\"no\\" frameborder=\\"0\\" style=\\"border:none; overflow:hidden; width:100px; height:90px;\\" allowTransparency=\\"true\\"><\\/iframe><\\/div><div id=\\"nuzulul_friend_box\\"><iframe src=\\"\/\/www.facebook.com\/plugins\/follow.php?href=https%3A%2F%2Fwww.facebook.com%2Fnuzulz&layout=box_count&show_faces=false&colorscheme=light&font&width=100&appId=172259479541279\\" scrolling=\\"no\\" frameborder=\\"0\\" style=\\"border:none; overflow:hidden; width:100px;\\" allowTransparency=\\"true\\"><\\/iframe><\\/div><div id=\\"nuzulul_friend_likeface\\"><iframe src=\\"\/\/www.facebook.com\/plugins\/like.php?href=https%3A%2F%2Ffacebook.com%2Fnuzulhook&send=false&layout=standard&width=500&show_faces=true&font&colorscheme=light&action=like&height=80&appId=172259479541279\\" scrolling=\\"no\\" frameborder=\\"0\\" style=\\"border:none; overflow:hidden; width:500px; height:80px;\\" allowTransparency=\\"true\\"><\\/iframe><\\/div><\\/div><div id=\\"nuzulul_likebox\\"><iframe src=\\"\/\/nuzulul.github.com\/ngawur\/leftzul.html\\" scrolling=\\"no\\" frameborder=\\"0\\" style=\\"border:none; overflow:hidden; width:300px; height:500px;\\" allowTransparency=\\"true\\"><\\/iframe><iframe src=\\"\/\/nuzulul.github.com\/ngawur\/tweetnuzulul.html\\" scrolling=\\"no\\" frameborder=\\"0\\" style=\\"border:none; overflow:hidden; width:320px; height:500px;\\" allowTransparency=\\"true\\"><\\/iframe><iframe src=\\"\/\/nuzulul.github.com\/ngawur\/tweetszul.html\\" scrolling=\\"no\\" frameborder=\\"0\\" style=\\"border:none; overflow:hidden; width:300px; height:500px;\\" allowTransparency=\\"true\\"><\\/iframe><\\/div><div id=\\"nuzulul_footer\\">Nuzulhook Official Site v2. Copyright © 2011-2013 <a href=\\"https:\/\/plus.google.com\/113810582017056258327?rel=author\\">Nuzulul Zulkarnain Haq<\/a>. All rights reserved.<\\/br>Seluruh artikel di nuzulul-fkp09.web.unair.ac.id dapat anda perbanyak, cetak, modifikasi dan distribusikan secara bebas asal tetap mencantumkan nama penulis dan URL lengkap artikel. <\\/br>Powered by Universitas Airlangga<\\/div><div id=\\"nuzulul_footer_nav\\"><li><a href=\\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24176.html\\">ABOUT<\\/a><\\/li><li><a href=\\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24192.html\\">DOWNLOAD<\/a><\\/li><li><a href=\\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24183.html\\">SAHABAT<\/a><\\/li><li><a href=\\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24186.html\\">BUKU TAMU<\/a><\\/li><li><a href=\\"http:\/\/nuzulul-fkp09.web.unair.ac.id\/artikel_detail-24196.html\\">ALBUM<\/a><\\/li><\\/div><\\/div>\";");
document.write("document.getElementById('site_title').innerHTML = \"<h1>Learning, Researching, Developing and Sharing<\\/h1><h2>Nuzulhook Official Site<\\/h2>\";");
document.write("document.getElementsByName('form3')[0].innerHTML = '<div class=\"fb-comments\" data-href=\"\" data-width=\"430\" data-num-posts=\"10\"><\/div>';");
document.write("(function(d, s, id) {");
document.write("  var js, fjs = d.getElementsByTagName(s)[0];");
document.write("  if (d.getElementById(id)) return;");
document.write("  js = d.createElement(s); js.id = id;");
document.write("  js.src = \"\/\/connect.facebook.net\/id_ID\/all.js#xfbml=1&appId=109267179132135\";");
document.write("  fjs.parentNode.insertBefore(js, fjs);");
document.write("}(document, 'script', 'facebook-jssdk'));");
document.write("}");
document.write("");
document.write("window.onload = loadScript;");
document.write("<\/script>");
